[versions]
# project modules version
p-root = "1.0.3"
p-honoka-gradle-utils = "1.0.3"
p-honoka-basic-plugin = "1.0.3"
p-honoka-android-plugin = "1.0.1"

# dependencies version
d-honoka-gradle-utils = "1.0.3"
d-honoka-basic-plugin = "1.0.3"
android-gradle-plugin = "8.0.0"

[libraries]
honoka-gradle-utils = { module = "de.honoka.gradle:honoka-gradle-utils", version.ref = "d-honoka-gradle-utils" }
honoka-basic-plugin = { module = "de.honoka.gradle.plugin:honoka-basic-plugin", version.ref = "d-honoka-basic-plugin" }
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "android-gradle-plugin" }
