name: Gradle CI

env:
  CIB_DOWNLOADER: https://mirrors.honoka.de/ci-builders/downloader.sh
  CIB_VERSION: 1.0.2
  CIB_GIT_INFO: ${{ secrets.CIB_GIT_INFO }}
  REMOTE_MAVEN_REPO_URL: ${{ secrets.REMOTE_MAVEN_REPO_URL }}

jobs:
  gradle-ci:
    name: Gradle CI
    runs-on: ubuntu-latest
    env:
      CIB_ARTIFACT_NAME: maven-repo-changes
    steps:
      - name: Download CI Builders
        run: |
          set -e
          curl -L --fail -o download-cib.sh $CIB_DOWNLOADER
          chmod +x download-cib.sh && ./download-cib.sh
      - uses: actions/checkout@v4
        with:
          path: repo
          submodules: recursive
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          # 通过预定义的包管理器之一管理的依赖项的快速设置缓存
          # 它可以是maven、gradle或sbt之一
          cache: gradle
      - name: Build with Gradle and publish to Maven repository
        run: |
          ./ci-builders/scripts/run.sh gradle-library publish
      - name: Upload the changes of Maven repository as artifact
        uses: actions/upload-artifact@v4
        with:
          # 指定要上传的目录在上传到当前Actions运行实例的Artifacts当中时要使用的名字
          name: ${{ env.CIB_ARTIFACT_NAME }}
          # 要上传的目录路径（以workspace为相对路径起始点）
          path: ${{ env.CIB_ARTIFACT_NAME }}

on:
  push:
    branches:
      - dev
    paths-ignore:
      - 'docs/**'
      - 'files/**'
      - '**/.gitignore'
      - 'LICENSE'
      - 'README.md'
